In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("carData.csv",names=["buying","maint","doors","persons","lug_boot","safety","classes"])

In [3]:
df.describe()

       buying maint doors persons lug_boot safety classes
count    1728  1728  1728    1728     1728   1728    1728
unique      4     4     4       3        3      3       4
top      high  high     3       2      med   high   unacc
freq      432   432   432     576      576    576    1210

In [4]:
df

     buying  maint  doors persons lug_boot safety classes
0     vhigh  vhigh      2       2    small    low   unacc
1     vhigh  vhigh      2       2    small    med   unacc
2     vhigh  vhigh      2       2    small   high   unacc
3     vhigh  vhigh      2       2      med    low   unacc
4     vhigh  vhigh      2       2      med    med   unacc
5     vhigh  vhigh      2       2      med   high   unacc
6     vhigh  vhigh      2       2      big    low   unacc
7     vhigh  vhigh      2       2      big    med   unacc
8     vhigh  vhigh      2       2      big   high   unacc
9     vhigh  vhigh      2       4    small    low   unacc
10    vhigh  vhigh      2       4    small    med   unacc
11    vhigh  vhigh      2       4    small   high   unacc
12    vhigh  vhigh      2       4      med    low   unacc
13    vhigh  vhigh      2       4      med    med   unacc
14    vhigh  vhigh      2       4      med   high   unacc
15    vhigh  vhigh      2       4      big    low   unacc
16    vhigh  vhigh      2       4      big    med   unacc
17    vhigh  vhigh      2       4      big   high   unacc
18    vhigh  vhigh      2    more    small    low   unacc
19    vhigh  vhigh      2    more    small    med   unacc
20    vhigh  vhigh      2    more    small   high   unacc
21    vhigh  vhigh      2    more      med    low   unacc
22    vhigh  vhigh      2    more      med    med   unacc
23    vhigh  vhigh      2    more      med   high   unacc
24    vhigh  vhigh      2    more      big    low   unacc
25    vhigh  vhigh      2    more      big    med   unacc
26    vhigh  vhigh      2    more      big   high   unacc
27    vhigh  vhigh      3       2    small    low   unacc
28    vhigh  vhigh      3       2    small    med   unacc
29    vhigh  vhigh      3       2    small   high   unacc
...     ...    ...    ...     ...      ...    ...     ...
1698    low    low      4    more      big    low   unacc
1699    low    low      4    more      big    med    good
1700    low    low      4    more      big   high   vgood
1701    low    low  5more       2    small    low   unacc
1702    low    low  5more       2    small    med   unacc
1703    low    low  5more       2    small   high   unacc
1704    low    low  5more       2      med    low   unacc
1705    low    low  5more       2      med    med   unacc
1706    low    low  5more       2      med   high   unacc
1707    low    low  5more       2      big    low   unacc
1708    low    low  5more       2      big    med   unacc
1709    low    low  5more       2      big   high   unacc
1710    low    low  5more       4    small    low   unacc
1711    low    low  5more       4    small    med     acc
1712    low    low  5more       4    small   high    good
1713    low    low  5more       4      med    low   unacc
1714    low    low  5more       4      med    med    good
1715    low    low  5more       4      med   high   vgood
1716    low    low  5more       4      big    low   unacc
1717    low    low  5more       4      big    med    good
1718    low    low  5more       4      big   high   vgood
1719    low    low  5more    more    small    low   unacc
1720    low    low  5more    more    small    med     acc
1721    low    low  5more    more    small   high    good
1722    low    low  5more    more      med    low   unacc
1723    low    low  5more    more      med    med    good
1724    low    low  5more    more      med   high   vgood
1725    low    low  5more    more      big    low   unacc
1726    low    low  5more    more      big    med    good
1727    low    low  5more    more      big   high   vgood

[1728 rows x 7 columns]

In [5]:
df.groupby(by=["classes"]).count()

         buying  maint  doors  persons  lug_boot  safety
classes
acc         384    384    384      384       384     384
good         69     69     69       69        69      69
unacc      1210   1210   1210     1210      1210    1210
vgood        65     65     65       65        65      65

In [6]:
df.pivot_table(index="buying",columns="classes",values="classes",aggfunc="count")

ValueError: Grouper for 'classes' not 1-dimensional

In [7]:
lista_buy = df["buying"].unique()

In [8]:
quantidade,w = df[df["classes"]=="unacc"].shape

In [10]:
lista_buy

array(['vhigh', 'high', 'med', 'low'], dtype=object)

In [11]:
quantidade

1210

In [12]:
dicionario = {}
total,_ = df.shape

In [13]:
for classificadores in df["classes"].unique():
    quantidade,_ = df[df["classes"]==classificadores].shape
    dicionario[classificadores] = quantidade/total
    print(quantidade)

1210
384
65
69

In [87]:
total,_ = df.shape
for atributo in df.columns[:-1]:
    for classificador in df["classes"].unique():
        for valoresDistintosColuna in df[atributo].unique():
            x ,_ =df[ (df[atributo] == valoresDistintosColuna) & (df["classes"] == classificador) ].shape
            y ,_ =df[ df[atributo] == valoresDistintosColuna ].shape
            dicionario[atributo,valoresDistintosColuna] = y/total
            dicionario[atributo,valoresDistintosColuna,classificador] = x / total
        
        quantidadeTotalClasse,_ = df[df["classes"]==classificador].shape
        dicionario[classificador] = quantidadeTotalClasse/total

In [78]:
df.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [79]:
dicionario["coluna","nome",2] = "danile"

In [88]:
dicionario

{('buying', 'vhigh'): 0.25,
 ('buying', 'vhigh', 'unacc'): 0.20833333333333334,
 ('buying', 'high'): 0.25,
 ('buying', 'high', 'unacc'): 0.1875,
 ('buying', 'med'): 0.25,
 ('buying', 'med', 'unacc'): 0.1550925925925926,
 ('buying', 'low'): 0.25,
 ('buying', 'low', 'unacc'): 0.14930555555555555,
 'unacc': 0.7002314814814815,
 ('buying', 'vhigh', 'acc'): 0.041666666666666664,
 ('buying', 'high', 'acc'): 0.0625,
 ('buying', 'med', 'acc'): 0.06655092592592593,
 ('buying', 'low', 'acc'): 0.05150462962962963,
 'acc': 0.2222222222222222,
 ('buying', 'vhigh', 'vgood'): 0.0,
 ('buying', 'high', 'vgood'): 0.0,
 ('buying', 'med', 'vgood'): 0.015046296296296295,
 ('buying', 'low', 'vgood'): 0.022569444444444444,
 'vgood': 0.03761574074074074,
 ('buying', 'vhigh', 'good'): 0.0,
 ('buying', 'high', 'good'): 0.0,
 ('buying', 'med', 'good'): 0.013310185185185185,
 ('buying', 'low', 'good'): 0.02662037037037037,
 'good': 0.03993055555555555,
 ('maint', 'vhigh'): 0.25,
 ('maint', 'vhigh', 'unacc'): 0.20833333333333334,
 ('maint', 'high'): 0.25,
 ('maint', 'high', 'unacc'): 0.18171296296296297,
 ('maint', 'med'): 0.25,
 ('maint', 'med', 'unacc'): 0.1550925925925926,
 ('maint', 'low'): 0.25,
 ('maint', 'low', 'unacc'): 0.1550925925925926,
 ('maint', 'vhigh', 'acc'): 0.041666666666666664,
 ('maint', 'high', 'acc'): 0.06076388888888889,
 ('maint', 'med', 'acc'): 0.06655092592592593,
 ('maint', 'low', 'acc'): 0.05324074074074074,
 ('maint', 'vhigh', 'vgood'): 0.0,
 ('maint', 'high', 'vgood'): 0.007523148148148148,
 ('maint', 'med', 'vgood'): 0.015046296296296295,
 ('maint', 'low', 'vgood'): 0.015046296296296295,
 ('maint', 'vhigh', 'good'): 0.0,
 ('maint', 'high', 'good'): 0.0,
 ('maint', 'med', 'good'): 0.013310185185185185,
 ('maint', 'low', 'good'): 0.02662037037037037,
 ('doors', '2'): 0.25,
 ('doors', '2', 'unacc'): 0.1886574074074074,
 ('doors', '3'): 0.25,
 ('doors', '3', 'unacc'): 0.1736111111111111,
 ('doors', '4'): 0.25,
 ('doors', '4', 'unacc'): 0.16898148148148148,
 ('doors', '5more'): 0.25,
 ('doors', '5more', 'unacc'): 0.16898148148148148,
 ('doors', '2', 'acc'): 0.046875,
 ('doors', '3', 'acc'): 0.057291666666666664,
 ('doors', '4', 'acc'): 0.059027777777777776,
 ('doors', '5more', 'acc'): 0.059027777777777776,
 ('doors', '2', 'vgood'): 0.005787037037037037,
 ('doors', '3', 'vgood'): 0.008680555555555556,
 ('doors', '4', 'vgood'): 0.011574074074074073,
 ('doors', '5more', 'vgood'): 0.011574074074074073,
 ('doors', '2', 'good'): 0.008680555555555556,
 ('doors', '3', 'good'): 0.010416666666666666,
 ('doors', '4', 'good'): 0.010416666666666666,
 ('doors', '5more', 'good'): 0.010416666666666666,
 ('persons', '2'): 0.3333333333333333,
 ('persons', '2', 'unacc'): 0.3333333333333333,
 ('persons', '4'): 0.3333333333333333,
 ('persons', '4', 'unacc'): 0.18055555555555555,
 ('persons', 'more'): 0.3333333333333333,
 ('persons', 'more', 'unacc'): 0.1863425925925926,
 ('persons', '2', 'acc'): 0.0,
 ('persons', '4', 'acc'): 0.11458333333333333,
 ('persons', 'more', 'acc'): 0.1076388888888889,
 ('persons', '2', 'vgood'): 0.0,
 ('persons', '4', 'vgood'): 0.017361111111111112,
 ('persons', 'more', 'vgood'): 0.02025462962962963,
 ('persons', '2', 'good'): 0.0,
 ('persons', '4', 'good'): 0.020833333333333332,
 ('persons', 'more', 'good'): 0.019097222222222224,
 ('lug_boot', 'small'): 0.3333333333333333,
 ('lug_boot', 'small', 'unacc'): 0.2604166666666667,
 ('lug_boot', 'med'): 0.3333333333333333,
 ('lug_boot', 'med', 'unacc'): 0.22685185185185186,
 ('lug_boot', 'big'): 0.3333333333333333,
 ('lug_boot', 'big', 'unacc'): 0.21296296296296297,
 ('lug_boot', 'small', 'acc'): 0.06076388888888889,
 ('lug_boot', 'med', 'acc'): 0.078125,
 ('lug_boot', 'big', 'acc'): 0.08333333333333333,
 ('lug_boot', 'small', 'vgood'): 0.0,
 ('lug_boot', 'med', 'vgood'): 0.014467592592592593,
 ('lug_boot', 'big', 'vgood'): 0.023148148148148147,
 ('lug_boot', 'small', 'good'): 0.012152777777777778,
 ('lug_boot', 'med', 'good'): 0.013888888888888888,
 ('lug_boot', 'big', 'good'): 0.013888888888888888,
 ('safety', 'low'): 0.3333333333333333,
 ('safety', 'low', 'unacc'): 0.3333333333333333,
 ('safety', 'med'): 0.3333333333333333,
 ('safety', 'med', 'unacc'): 0.2065972222222222,
 ('safety', 'high'): 0.3333333333333333,
 ('safety', 'high', 'unacc'): 0.16030092592592593,
 ('safety', 'low', 'acc'): 0.0,
 ('safety', 'med', 'acc'): 0.10416666666666667,
 ('safety', 'high', 'acc'): 0.11805555555555555,
 ('safety', 'low', 'vgood'): 0.0,
 ('safety', 'med', 'vgood'): 0.0,
 ('safety', 'high', 'vgood'): 0.03761574074074074,
 ('safety', 'low', 'good'): 0.0,
 ('safety', 'med', 'good'): 0.022569444444444444,
 ('safety', 'high', 'good'): 0.017361111111111112}

In [112]:
lista = ["vhigh", "vhigh", "2", "2", "small", "low"]
#["buying","maint","doors","persons","lug_boot","safety","classes"]
lista
resultado = []

In [113]:
maior = (0,0)
for classificador in df["classes"].unique():
    prob = 1
    i=0
    print("classe = "+classificador)
    for nomeColuna in df.columns[:-1]:
        prob *= (dicionario[nomeColuna,lista[i],classificador] * dicionario[classificador] ) / dicionario[nomeColuna,lista[i]]
        i+=1
    resultado.append((classificador,prob))
resultado

[('unacc', 0.04826265223733016), ('acc', 0.0), ('vgood', 0.0), ('good', 0.0)]

In [109]:
for nomeColuna in df.columns[:-1]:
    print(nomeColuna)

buying
maint
doors
persons
lug_boot
safety